### PR TITLE
(Data Hup / Peerscout API): Add replicas to Peerscout API prod

### PR DESCRIPTION
**Pull request by HazalCiplak**
Added replicas to Peerscout API prod to increase availability

### CODE REVIEW

**Review by de-code — DISMISSED** [review]

**Comment by scottaubrey** [comment]
Hey @HazalCiplak - this isn't going to do what you want it to. 

This resource represents the HelmChart installation - the actual deployment resource is using the template in [data-science-dags](https://github.com/elifesciences/data-science-dags/blob/develop/charts/peerscout/templates/deployment.yaml). The value for replicas is `replicaCount`.

So with that change in place (and pushed) I can then verify what the helm chart will deploy:
```
> yq '.spec.values' deployments/peerscout/peerscout--prod.yaml |                        # get the values from the HelmRelease resource
helm template -f - ~/Sources/helm-charts/data-science-dags/charts/peerscout |           # get helm to display the output based on the values passed in through stdin
yq 'select(.kind == "Deployment")|.spec.replicas'                                       # select the Deployment resource and read the spec.replicas value
2
```

That looks good to me!

**Comment by de-code** [comment]
Well spotted. Thank you.

**Comment by HazalCiplak** [comment]
Thanks a lot Scott!

**Comment by scottaubrey** [comment]
Confirmed working correctly:

```
> kubectl get deployment -n peerscout
NAME              READY   UP-TO-DATE   AVAILABLE   AGE
peerscout--prod   2/2     2            2           576d
peerscout--stg    1/1     1            1           576d
```

**Comment by HazalCiplak** [comment]
```
> kubectl get pods -n peerscout

NAME                              READY   STATUS    RESTARTS       AGE
peerscout--prod-c687ff89c-tgtmq   1/1     Running   1 (107m ago)   179m
peerscout--prod-c687ff89c-z8prq   1/1     Running   6 (48m ago)    7h39m
peerscout--stg-7489c44bbb-66l2j   1/1     Running   0              7h39m
```

**Comment by de-code** [comment]
Need to maybe investigate why there are so many restarts.

**Pull request merged**
