### PR TITLE
Data hub test env

### PR DESCRIPTION
**Pull request by scottaubrey**
# Todo
- [x] Find out what differences there needs to be in this env
- [x] reencode all secrets with new names and namespaces
- [ ] ~Find out if `envsubst` can be used to simulate what `postBuild.substitute` would do in flux, and consider switching JSON patches for substitutions~
- [x] Make changes listed https://github.com/elifesciences/data-hub-issues/issues/418

# Description

This PR creates a new `--test` environment for data-hub available on `data-hub--test.elifesciences.org`. This adds new configs for ejp too.
It also changes data-hub-configs to be a configmapgenerator for easier maintenance of the config files.
I also renamed `europepmc-labslink--stg.config.yaml` to `europepmc-labslink--test.config.yaml` as it is a test ftp service, not a staging.

Summary of service configs used by each env
`--prod` uses:
- europepmc-labslink--prod
- s3-csv-data-pipeline--prod
- ejp-xml-data-pipeline--prod
`--stg` uses:
- europepmc-labslink--test
- s3-csv-data-pipeline--prod
- ejp-xml-data-pipeline--prod
`--test` uses:
- europepmc-labslink--test
- s3-csv-data-pipeline--test
- ejp-xml-data-pipeline--test

The `--test` env also uses s3 bucket named `test-elife-data-pipeline`, and `DEPLOYMENT_ENV`, `MATERIALIZE_BIGQUERY_VIEWS_DATASET` both set to `test`

### CODE REVIEW

**Comment by de-code** [comment]
Thank you @scottaubrey for doing that.

Just some thoughts (not sure how much warranted they are):

The main config is separated between `prod`, `staging` and `test`.
Having `staging` refer to config with `--prod` or `--test` config could potentially be confusing.
@HazalCiplak suggested to potentially remove the `--prod` suffix and just keep the `--test` suffix?
Maybe for the labslink config, another suffix other than `--test` might make it more obvious that it is not just for the `test` environment?
Still need to review it more.
I wouldn't take any immediate actions based on those comments, but what do you think?

**Comment by scottaubrey** [comment]
> Thank you @scottaubrey for doing that.
> 
> Just some thoughts (not sure how much warranted they are):
> 
> The main config is separated between `prod`, `staging` and `test`. Having `staging` refer to config with `--prod` or `--test` suffix could potentially be confusing. @HazalCiplak suggested to potentially remove the `--prod` suffix and just keep the `--test` suffix? Maybe for the labslink config, another suffix other than `--test` might make it more obvious that it is not just for the `test` environment? Still need to review it more. I wouldn't take any immediate actions based on those comments, but what do you think?

I agree, the number and type of variations is possibly getting to the slightly more confusing stage. The way I got my own head around it was to think of the config's with `--test` as their testing environments, not ours (if that makes sense). Then I could understand it. I like Hazal's suggestion that we keep the main prod versions of external services without a prefix, and add `--test` to those that are external test services.

I'm a little unsure what else to name either our or their test services though. They are the test services :) Any suggestions very welcome.

**Comment by scottaubrey** [comment]
@de-code @HazalCiplak  - I've updated the configs now to remove `--prod` suffixes. I've also added a comment on the stg  deployment to document that the the labslink `--test` is used because we can't use their prod service, and refers to their test environment, not ours.

**Review by de-code — APPROVED** [review]

**Comment by de-code** [comment]
> @de-code @HazalCiplak - I've updated the configs now to remove `--prod` suffixes. I've also added a comment on the stg deployment to document that the the labslink `--test` is used because we can't use their prod service, and refers to their test environment, not ours.

Thank you again, and apologies for taking longer than usual to have a more thorough look.

**Comment by de-code** [comment]
I was going to add new configuration soon. Would probably be good to have this merged before.

**Pull request merged**
