### PR TITLE
configure compressed labslink links xml filename

### PR DESCRIPTION
**Pull request by de-code**
related to https://github.com/elifesciences/data-hub-core-airflow-dags/pull/959

Configure a compressed links XML filename.

### CODE REVIEW

**Comment by de-code** [comment]
@scottaubrey the e2e test seem to be failing due to a timeout. Is that work-in progress or related to this PR?

**Comment by scottaubrey** [comment]
Yesterday the sealed-secrets images disappeared, and the e2e test pull in all the deployments into a new cluster - so they were failing for most of the afternoon.

bitnami released a new version of the helm chart pointing to dockerhub instead, and I've updated and merged this in this morning. I'm hoping this should fix the CI test, but if not I'll look into it.

**Comment by scottaubrey** [comment]
But the bottom line is, it's unlikely this change that's caused CI to fail, so this will be safe to merge

**Review by scottaubrey — APPROVED** [review]

**Comment by scottaubrey** [comment]
Tests pass now, sorry for the delay.

**Review by HazalCiplak — APPROVED** [review]

**Comment by de-code** [comment]
That is perfect, thank you.

**Pull request merged**
